FROM opensearchproject/opensearch-dashboards:1.1.0@sha256:52e6af201ed5c0cf508bf0d28b240ad730d88138bf8bb8d4db53554820ea2cba
RUN /usr/share/opensearch-dashboards/bin/opensearch-dashboards-plugin remove securityDashboards
COPY --chown=opensearch-dashboards:opensearch-dashboards opensearch_dashboards.yml /usr/share/opensearch-dashboards/config/
